
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://1.15.82.146:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: admin
    password: admin@cmcc

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
